version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: [ "poetry", "run", "python", "app.py"] 
    depends_on:
      - db
  db:
    image: postgres:16
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
